const state = { commands: [], categories: [], query: '', category: 'all', selectedId: null, view: 'list' };
const icons = { all:'✨', visual:'🎨', perspektif:'🔍', sistem:'⚙️', kreatif:'💡', belajar:'📚', kritis:'🧠', bisnis:'💼', produktivitas:'🚀', komunikasi:'✉️', pengembangan:'🌱', ai:'🤖', data:'📊', multibahasa:'🌐', produk:'📱', interpersonal:'🤝', coding:'💻', marketing:'📈', education:'🎓', trading:'💹', design:'🖌️' };
const examples = {
  '/poster': 'Buatkan poster HUT RI ke-81 Indonesia, modern minimalis dengan tema budaya Nusantara. Gunakan komposisi premium, tipografi tegas, ornamen budaya Indonesia secara subtle, aksen merah putih, dan layout Instagram 1:1.',
  '/infographic': 'Buatkan infografis tentang alur bisnis maklon kosmetik dari konsultasi, formulasi, produksi, BPOM, hingga produk siap jual. Gunakan gaya modern, bersih, mudah dipahami, dan profesional.',
  '/carousel': 'Buatkan carousel Instagram 7 slide tentang 5 kesalahan pemula saat memulai bisnis skincare. Gunakan storytelling singkat, visual modern, CTA kuat, dan gaya premium.',
  '/thumbnail': 'Buatkan konsep thumbnail YouTube tentang cara menghasilkan uang dari bisnis skincare dengan headline kuat, visual dramatis, kontras tinggi, dan fokus pada curiosity gap.',
  '/seo': 'Optimalkan artikel tentang maklon skincare untuk keyword utama "maklon skincare" dengan struktur heading, search intent, internal link, meta title, meta description, dan CTA.',
  '/copywriting': 'Buatkan copywriting landing page untuk layanan maklon kosmetik MOQ 2.000 pcs dengan benefit FREE BPOM, FREE Halal, FREE Sample, dan FREE Revision 3x.',
  '/marketing': 'Buatkan strategi campaign digital 30 hari untuk bisnis maklon kosmetik yang menargetkan calon pemilik brand usia 20–60 tahun melalui Instagram dan TikTok.',
  '/website': 'Buatkan struktur landing page website premium untuk layanan maklon skincare dengan hero section, benefit, proses produksi, social proof, FAQ, dan CTA konsultasi.',
  '/coding': 'Audit dan perbaiki JavaScript frontend ini. Prioritaskan bug, keamanan XSS, performa, accessibility, dan jangan mengubah behavior yang sudah bekerja.',
  '/visualize': 'Visualisasikan konsep bisnis maklon kosmetik sebagai diagram sederhana yang menunjukkan hubungan antara brand owner, formulator, pabrik, BPOM, dan konsumen.',
  '/mindmap': 'Buatkan mind map lengkap untuk memulai bisnis skincare dari riset pasar, positioning, formulasi, produksi, legalitas, branding, marketing, hingga scale-up.'
};
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value='') => String(value).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const categoryName = id => state.categories.find(c => c.id === id)?.name || id || 'General';
const categoryCount = id => state.commands.filter(c => c.categoryId === id).length;
function filtered() { const q=state.query.trim().toLowerCase(); return state.commands.filter(c => (state.category==='all'||c.categoryId===state.category) && (!q||`${c.name} ${c.description} ${c.template} ${categoryName(c.categoryId)}`.toLowerCase().includes(q))); }
function generateTemplate(c) { return `${c.name}\n\nTolong buatkan ${String(c.description).toLowerCase()} mengenai topik berikut:\n\n[MASUKKAN TOPIK/IDE ANDA DI SINI]\n\nPastikan format dan gayanya sesuai dengan perintah tersebut.`; }
function generateExample(c) { return examples[c.name] || `${c.name}\n\nBuatkan ${String(c.description).toLowerCase()} untuk topik [TOPIK ANDA]. Sesuaikan hasil dengan kebutuhan saya, gunakan struktur yang jelas, detail yang relevan, dan gaya profesional.`; }
function toast(message) { const el=document.createElement('div'); el.className='toast'; el.textContent=message; document.body.appendChild(el); setTimeout(()=>{el.classList.add('fade');setTimeout(()=>el.remove(),300)},1700); }
async function copyText(text, message='Template tersalin!') { try { await navigator.clipboard.writeText(text); } catch { const ta=document.createElement('textarea'); ta.value=text; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove(); } toast(message); }
function renderShell() {
  document.querySelector('#root').innerHTML = `<div class="app"><aside class="sidebar"><div class="brand"><span class="brand-icon">✨</span><div><strong>Peta Perintah</strong><small>193 COMMANDS · V2</small></div></div><nav id="category-list"></nav></aside><main class="main"><header class="topbar"><label class="search"><span>⌕</span><input id="search" type="search" placeholder="Cari dari 193 perintah (nama atau fungsi)..." autocomplete="off"></label><div class="view-switch"><button data-view="list" class="active" title="List">☷</button><button data-view="grid" title="Grid">▦</button></div></header><section class="content"><div class="page-title"><div><p>COMMAND DATA V2 · PRODUCTION</p><h1>193 Perintah Rahasia ChatGPT</h1><span id="result-meta">Memuat data…</span></div><button id="reset" class="reset">Reset</button></div><div id="results"></div></section><footer>Disusun oleh Samson — Edisi 2026 · <span id="data-status">Data V2: —</span></footer></main><div id="modal-root"></div></div>`;
}
function renderCategories() { const all=[{id:'all',name:'Semua'} ,...state.categories]; $('#category-list').innerHTML=all.map(c=>`<button class="category ${state.category===c.id?'active':''}" data-category="${escapeHtml(c.id)}"><span class="cat-icon">${icons[c.id]||'•'}</span><span class="cat-label">${escapeHtml(c.name)}</span><b>${c.id==='all'?state.commands.length:categoryCount(c.id)}</b></button>`).join(''); }
function renderResults() { const items=filtered(); $('#result-meta').textContent=`${items.length} dari ${state.commands.length} command`; if(!items.length){$('#results').innerHTML='<div class="empty"><div>⌕</div><h2>Tidak ada perintah yang cocok.</h2><p>Coba gunakan kata kunci lain.</p></div>';return;} const grouped={}; items.forEach(c=>(grouped[c.categoryId] ||= []).push(c)); $('#results').innerHTML=Object.entries(grouped).map(([cat,arr])=>`<section class="group"><div class="group-head"><h2><span>${icons[cat]||'•'}</span>${escapeHtml(categoryName(cat))}</h2><em>${arr.length} / ${categoryCount(cat)}</em></div><div class="command-list ${state.view==='grid'?'grid':''}">${arr.map(c=>`<article class="command-card" data-id="${c.id}"><div class="card-main">${state.view==='grid'?`<div class="big-icon">${icons[cat]||'•'}</div>`:''}<div class="command-line"><code>${escapeHtml(c.name)}</code><small>#${String(c.id).padStart(3,'0')}</small></div><p>${escapeHtml(c.description)}</p></div><button class="arrow" aria-label="Lihat detail">›</button></article>`).join('')}</div></section>`).join(''); }
function renderModal() { const c=state.commands.find(x=>x.id===state.selectedId); if(!c){$('#modal-root').innerHTML='';return;} const template=generateTemplate(c); const example=generateExample(c); $('#modal-root').innerHTML=`<div class="overlay" data-close="1"><div class="modal" role="dialog" aria-modal="true" aria-label="Detail ${escapeHtml(c.name)}"><header><div class="modal-title"><span>${icons[c.categoryId]||'•'}</span><div><h2>${escapeHtml(c.name)}</h2><small>${escapeHtml(categoryName(c.categoryId))} · #${String(c.id).padStart(3,'0')}</small></div></div><button class="close" data-close="1">×</button></header><div class="modal-body"><label>FUNGSI UTAMA</label><p class="function">${escapeHtml(c.description)}</p><label>CONTOH PENGGUNAAN</label><div class="example-wrap"><textarea id="example-text" readonly>${escapeHtml(example)}</textarea><button id="copy-example" title="Salin contoh">⧉</button></div><label>TEMPLATE PROMPT (SIAP SALIN)</label><div class="template-wrap"><textarea readonly>${escapeHtml(template)}</textarea><button id="copy" title="Salin">⧉</button></div><p class="hint">💡 Gunakan contoh sebagai referensi, lalu sesuaikan topik, target, gaya, dan kebutuhan Anda.</p></div><footer><button id="copy-example-close" class="secondary">⧉ &nbsp; Salin Contoh</button><button id="copy-close" class="primary">⧉ &nbsp; Salin Prompt & Tutup</button></footer></div></div>`; }
function render() { renderCategories(); renderResults(); }
async function loadData(){ try { const [cr,kr]=await Promise.all([fetch('/data/commands.json',{cache:'no-store'}),fetch('/data/categories.json',{cache:'no-store'})]); if(!cr.ok||!kr.ok) throw new Error(`HTTP ${cr.status}/${kr.status}`); state.commands=await cr.json(); state.categories=await kr.json(); if(!Array.isArray(state.commands)||!Array.isArray(state.categories)) throw new Error('Invalid payload'); $('#data-status').textContent=`Data V2: ${state.commands.length} command · ${state.categories.length} kategori`; render(); } catch(e){ console.error(e); $('#result-meta').textContent='Data gagal dimuat'; $('#data-status').textContent='Data V2: error'; $('#results').innerHTML='<div class="empty"><div>!</div><h2>Gagal memuat Command Data V2.</h2><p>Periksa pipeline data extraction dan schema validation.</p></div>'; } }
document.addEventListener('click', e=>{ const cat=e.target.closest('[data-category]'); if(cat){state.category=cat.dataset.category;state.selectedId=null;render();return;} const card=e.target.closest('[data-id]'); if(card){state.selectedId=Number(card.dataset.id);renderModal();return;} const view=e.target.closest('[data-view]'); if(view){state.view=view.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===view));renderResults();return;} if(e.target.closest('#reset')){$('#search').value='';state.query='';state.category='all';render();return;} if(e.target.closest('[data-close]')){state.selectedId=null;renderModal();return;} if(e.target.closest('#copy-example')){const c=state.commands.find(x=>x.id===state.selectedId);if(c)copyText(generateExample(c),'Contoh tersalin!');return;} if(e.target.closest('#copy-example-close')){const c=state.commands.find(x=>x.id===state.selectedId);if(c){copyText(generateExample(c),'Contoh tersalin!');state.selectedId=null;renderModal();}return;} if(e.target.closest('#copy')){const c=state.commands.find(x=>x.id===state.selectedId);if(c)copyText(generateTemplate(c));return;} if(e.target.closest('#copy-close')){const c=state.commands.find(x=>x.id===state.selectedId);if(c){copyText(generateTemplate(c));state.selectedId=null;renderModal();}}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.query=e.target.value;renderResults();}});
renderShell(); loadData();
